gmp_env/gmp/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_chat, name='newchat'),
]

gmp_env/gmp/gmp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('chat.urls')),
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gmp_env/gmp/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('newitem/', views.new_item, name='newitem'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/deleteitem/', views.delete_item, name='deleteitem'),
    path('<int:pk>/edititem/', views.edit_item, name='edititem'),
]

gmp_env/gmp/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)
    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    posted_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    posted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

gmp_env/gmp/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

gmp_env/gmp/item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewItemForm,EditItemForm
from .models import Item, Category

def items(request):
    query = request.GET.get('query','')
    categories = Category.objects.all()
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category = item.category, is_sold = False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html',{
        'item': item,
        'related_items': related_items
    })

@login_required
def new_item(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.posted_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'New Item',
    })

@login_required
def delete_item(request, pk):
    item = get_object_or_404(Item, pk=pk, posted_by=request.user)
    item.delete()

    return redirect('dashboard:index')

@login_required
def edit_item(request,pk):
    item = get_object_or_404(Item, pk=pk, posted_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'Edit Item',
    })

gmp_env/gmp/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500 font-mono"><strong>Selling Price: </strong>${{ item.price }}</p>
        <p class="text-gray-500 font-mono"><strong>Seller: </strong>{{ item.posted_by.username }}</p>
        {% if item.description %}
        <p class="text-gray-700 font-mono">
            <strong class="text-gray-500 font-mono">Description: </strong><br>
            {{ item.description }}
        </p>
        {% endif %}

        {% if request.user == item.posted_by %}
                <a href="{% url 'item:edititem' item.id %}" class="inline-block mt-4 px-4 py-2 text-lg font-mono bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:deleteitem' item.id %}" class="inline-block mt-4 px-4 py-2 text-lg font-mono bg-red-500 text-white rounded-xl">Delete</a>
        {% else %}
            <a href="{% url 'chat:newchat' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-mono bg-teal-500 text-white rounded-xl hover:bg-teal-700"> Contact Seller</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-mono">Items you might like...</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl font-mono">{{ item.name }}</h2>
                        <p class="text-gray-500 font-mono">Selling Price: ${{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

gmp_env/gmp/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<h1 class="mb-6 text-3xl font-mono">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4 font-mono">
        {{ form.as_p }}
    </div>
    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form%}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="mt-4 py-2 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white font-mono">Submit</button>
</form>
{% endblock %}

gmp_env/gmp/item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Browse Items{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1 px-2">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="mt-2 w-full py-4 px-6 border rounded-xl font-mono" type="text" value="{{ query }}" placeholder="Search the item you need...">

                <button class="mt-2 py-2 px-4 text-lg bg-teal-500 text-white rounded-xl font-mono">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-mono">Categories</p>
            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl font-mono {% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <ul>
                <li>
                    <a href="{% url 'item:items' %}" class="mt-2 py-2 px-4 inline-block bg-red-500 text-lg rounded-xl text-white font-mono">Clear Filters</a>
                </li>
            </ul>

        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl font-mono">{{ item.name }}</h2>
                                <p class="text-gray-500 font-mono">Selling Price: ${{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}