gmp_env/gmp/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_chat, name='newchat'),
]

gmp_env/gmp/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

gmp_env/gmp/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

gmp_env/gmp/gmp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('chat.urls')),
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gmp_env/gmp/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('newitem/', views.new_item, name='newitem'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/deleteitem/', views.delete_item, name='deleteitem'),
    path('<int:pk>/edititem/', views.edit_item, name='edititem'),
]

gmp_env/gmp/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Please enter your username',
        'class': 'w-full py-2 px-4 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Please enter your password',
        'class': 'w-full py-2 px-4 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Please enter your username',
        'class': 'w-full py-2 px-4 rounded-xl'
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Please enter your email address',
        'class': 'w-full py-2 px-4 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Please enter your password',
        'class': 'w-full py-2 px-4 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Please re-enter your password',
        'class': 'w-full py-2 px-4 rounded-xl'
    }))

gmp_env/gmp/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold = False)
    categories = Category.objects.all()
    return render(request, 'core/index.html',{
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html',{
        'form': form
    })

gmp_env/gmp/core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        
        <title>{% block title %}{% endblock %} | Graduate Market Place</title>
    </head>

    <body>
        <header class="text-gray-600 font-mono">
            <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
                <a href="/" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
                    <img src="../../../media/assets/gmplogo.png" class="max-w-full h-auto rounded-full h-10 w-10" alt="GMP Logo">
                    <span class="ml-3 text-xl">Graduate Market Place</span> 
                </a> 
                <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
                    <a href="{% url 'item:newitem' %}" class="mr-5 underline decoration-transparent hover:decoration-inherit text-gray-400 hover:text-gray-900 transition duration-300 ease-in-out">Add Item</a>
                    <a href="{% url 'item:items' %}" class="mr-5 underline decoration-transparent hover:decoration-inherit text-gray-400 hover:text-gray-900 transition duration-300 ease-in-out">Browse Items</a>

                    {% if request.user.is_authenticated %}
                        <a href="{% url 'chat:inbox' %}" class="mr-5 underline decoration-transparent hover:decoration-inherit text-gray-400 hover:text-gray-900 transition duration-300 ease-in-out">Inbox</a>
                        <a href="{% url 'dashboard:index' %}" class="mr-5 underline decoration-transparent hover:decoration-inherit text-gray-400 hover:text-gray-900 transition duration-300 ease-in-out">Dashboard</a>
                    {% else %}
                        <a href="{% url 'core:signup' %}" class="mr-5 underline decoration-transparent hover:decoration-inherit text-gray-400 hover:text-gray-900 transition duration-300 ease-in-out">Sign up</a>
                        <a href="{% url 'core:login' %}" class="mr-5 underline decoration-transparent hover:decoration-inherit text-gray-400 hover:text-gray-900 transition duration-300 ease-in-out">Log in</a>
                    {% endif %}
                </nav>
                {% if request.user.is_authenticated %}
                <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"><a href="{% url 'core:logout' %}">Logout</a></button>
                {% endif %}
            </div>
        </header>


        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="p-4 bg-white sm:p-6 bg-gray-900">
            <div class="md:flex md:justify-between">
                <div class="mb-6 md:mb-0">
                    <a href="/" class="flex items-center">
                        <img src="../../../media/assets/gmplogo.png" class="max-w-full rounded-full mr-3 h-10 w-10" alt="GMP Logo">
                        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-gray-900">Graduate Market Place</span>
                    </a>
                    <p class="text-lg font-mono text-gray-500">A one-stop marketplace for students to sell and buy used or new products.</p>
                </div>
                <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
                    <div>
                        <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-gray-600">Resources</h2>
                        <ul class="text-gray-600 dark:text-gray-400">
                            <li class="mb-4">
                                <a href="https://www.djangoproject.com/start/overview/" class="hover:underline">Django</a>
                            </li>
                            <li>
                                <a href="https://tailwindcss.com/" class="hover:underline">Tailwind CSS</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-gray-600">Follow</h2>
                        <ul class="text-gray-600 dark:text-gray-400">
                            <li class="mb-4">
                                <a href="https://www.linkedin.com/in/polu-tharun-kumar-reddy/" class="hover:underline ">LinkedIn</a>
                            </li>
                            <li>
                                <a href="https://discordapp.com/users/763436847296151612" class="hover:underline">Discord</a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-gray-600">Legal</h2>
                        <ul class="text-gray-600 dark:text-gray-400">
                            <li class="mb-4">
                                <a href="#" class="hover:underline">Privacy Policy</a>
                            </li>
                            <li>
                                <a href="#" class="hover:underline">Terms &amp; Conditions</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
            <div class="sm:flex sm:items-center sm:justify-between">
                <p class="text-gray-500 text-sm sm:text-center dark:text-gray-400 sm:text-left">© 2023
                    <a href="https://www.linkedin.com/in/polu-tharun-kumar-reddy/" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">Tharun Kumar Reddy Polu</a>
                    . All Rights Reserved.
                </p>
                <div class="flex mt-4 space-x-6 sm:justify-center sm:mt-0">
                    <a href="https://www.facebook.com/Tharunprince111" class="text-gray-500 hover:text-gray-900 dark:hover:text-gray-900">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" /></svg>
                        <span class="sr-only">Facebook page</span>
                    </a>
                    <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-gray-900">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" /></svg>
                        <span class="sr-only">Instagram page</span>
                    </a>
                    <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-gray-900">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" /></svg>
                        <span class="sr-only">Twitter page</span>
                    </a>
                    <a href="https://github.com/TharunKumarReddyPolu" class="text-gray-500 hover:text-gray-900 dark:hover:text-gray-900">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" /></svg>
                        <span class="sr-only">GitHub account</span>
                    </a>
                </div>
            </div>
          </footer>
    </body>
</html>

gmp_env/gmp/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

gmp_env/gmp/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Hello{% endblock %}

{% block content %}

    <section class="text-gray-600 body-font">
        <h2 class="mb-6 mt-12 text-2xl text-center font-mono underline">Latest Items</h2>
        <div class="container px-5 py-15 mx-auto">
          <div class="flex flex-wrap -m-4">
            {% for item in items %}
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full border-x-2 border-y-2">
              <a class="block relative h-48 rounded overflow-hidden" href="{% url 'item:detail' item.id %}">
                <div>
                    <img class="object-cover object-center w-full h-full block" src="{{ item.image.url }}">
                </div>
              </a>
              <div class="mt-4">
                <h2 class="text-gray-900 title-font text-lg font-medium">{{ item.name }}</h2>
                <p class="mt-1">Selling Price: ${{ item.price }}</p>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
    </section>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-mono underline">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl font-mono">{{ category.name }}</h2>
                        <p class="text-gray-500 font-mono">{{ category.items.count }} items</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

gmp_env/gmp/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl font-mono">Log in</h1>
    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username </label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password </label>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form%}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Log in</button>
    </form>
</div>
{% endblock %}

gmp_env/gmp/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl font-mono text-center">Sign Up</h1>
    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2 font-mono">Username </label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2 font-mono">Email </label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2 font-mono">Password </label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2 font-mono">Confirm Password </label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form%}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="mt-2 py-2 px-4 bg-teal-500 hover:bg-teal-700 rounded-full text-white font-mono">Submit</button>
    </form>
</div>
{% endblock %}